# Generated by Django 5.2.1 on 2025-07-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_is_verified_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('ATS', 'ATS'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
