# Generated by Django 5.2.1 on 2025-07-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('ATS', 'ATS'), ('Admin', 'Admin'), ('Director', 'Director'), ('Medecin', 'Medecin'), ('Assistant', 'Assistant')], max_length=20),
        ),
    ]
