# Generated by Django 5.2.1 on 2025-07-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher'), ('ATS', 'ATS'), ('Admin', 'Admin'), ('Director', 'Director'), ('Medecin', 'Doctor'), ('Assistant', 'Assistant-Doctor'), ('Patient', 'Patient')], max_length=20),
        ),
    ]
